### ISSUE TITLE
Sources for Axios Client

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin-meta#10]
Currently, we build and publish the Axios client manually. Build scripts, documentation for building and sources are nowhere to be seen, we don't provide anything else but the npm package.

Specially needed for jellyfin-chromecast implementation

**Comment by nielsvanvelzen** [comment]
I think we could create a repository for it that uses a scheduled action to build & manage itself, that way we can detach it from the server repository too. It would run every day and look for new stable/unstable releases and when found build itself and push it to a branch. Another actions would react to pushes to the repo and publish to NPM.

**Comment by ferferga** [comment]
Had some spare time to create a quick automated repository for this, which can be expanded in the future for automated publishing to npm: https://github.com/ferferga/jellyfin-client-axios

We can consider transferring it to the org.

**Comment by nielsvanvelzen** [comment]
I guess this issue can be closed now?
