### ISSUE TITLE
Cast receiver configuration

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-meta#45]
To ease cast client development and make it easier to use third-party/self hosted implementations I propose some changes to how we deal with the cast receiver id in the server/web. The main changes of this proposal are:

- Configure the available cast receivers
  - Mainly making it possible to host your own without modifying jellyfin-web (or the native clients that implement casting).
- Remove the hard coded receiver ids from the frontend

I'm searching for someone to tackle the server part of this proposal. I can do the web part myself (although if someone from the web team wants to do that, please do!).

**Jellyfin server changes**

- Add "CastReceiverApplications" to system.xml
  - Will have a name & id for the receivers
  - Default to two entries: `Stable (F007D354)` and `Unstable (6F511C87)` (our current application ids)

- Add "CastReceiverApplications" to `/System/Info` endpoint
  Sample JSON:
  ```json
  {
	"CastReceiverApplications": [
		{
			"id": "F007D354",
			"name": "Stable"
		}
	]
  }
  ```
  Clients should use the user preferred cast client or they must use the first returned application.

- Add "CastReceiver" to UserConfiguration
  - The value is the id of the cast receiver
  - Must be one of the entries in system.xml when the value is updated (doesn't need to be validated on GET)
  - Defaults to first entry in CastReceiverApplications

- Migrate the existing chromecastVersion property from the usersettings to the new user configuration property

**Jellyfin web changes**

- Use the CastReceiverApplications value from the system info in the user playback settings page
- Use the CastReceiver value from the user config when using cast
- Remove hardcoded cast client values

---

This effectively supersedes #7 (which I noticed existed after I made this draft).

**Comment by crobibero** [comment]
I'll work on the server part 👍

**Comment by nielsvanvelzen** [comment]
I can work on the web part in about a week or so, unless someone else volunteers to do the web part. It should be fairly easy with basic knowledge about the jellyfin-web codebase.

**Comment by BloodyIron** [comment]
🍿

**Comment by nielsvanvelzen** [comment]
With half of the implementation already done this is extremely likely to be in 10.9 yes.

**Comment by nielsvanvelzen** [comment]
Closing as resolved. Both the server and client changes are merged for 10.9!

**Comment by BloodyIron** [comment]
Will these settings be configurable via the webGUI for the Admin section of Jellyfin? In... addition to CLI?

**Comment by nielsvanvelzen** [comment]
No you cannot change the list of cast receivers via the webui/cli. You'll need to modify the configuration file. This is done because this configuration is only for advanced use cases like development or when self-hosting the receiver, both require a Google Cast developer account (which is not free) and the expectation is that not a lot of users will do this.

The ids are not git hashes, those are the cast receiver ids Google generates.

**Comment by BloodyIron** [comment]
> both require a Google Cast developer account (which is not free)

Well I didn't even know this part lol! That's absolute bonkers self-hosting that data (as opposed to pulling from github?) requires a Google Cast developer account. Does the github (current?) method involve a Google Cast developer account somehow? 🤔

**Comment by Maxr1998** [comment]
The current method uses cast clients hosted by the Jellyfin team.
