### ISSUE TITLE
Too many GetUserById calls

### ISSUE THREAD

**Issue by goremykin** [jellyfin/jellyfin-meta#73]
I have noticed that `userManager.GetUserById` is called dozens of times when I open the home screen. So I decided to measure how much time it takes in total and how often is it called when I open the home screen.
It is called 66 times and it takes 3 seconds in total just to show the home screen.

I think these numbers are quite big and we should discuss how to reduce them.
Maybe some context where we store a current user can be a starting point for this discussion?

**Comment by crobibero** [comment]
Sounds like you are referring to the server code.
The call you are looking at is cached and wouldn't be the part that delaying the home screen render.

**Comment by goremykin** [comment]
@crobibero, Ah, I see. Once the dashboard is loaded, these calls take a little time - probably due to the caching you mentioned. Thanks!
